name: cadiionogram
channels:
  - conda-forge
  - defaults
dependencies:
  - joblib
  - matplotlib
  - nomkl
  - nodejs
  - numpy
  - pandas
  - pip
  - pyarrow
  - pyside6
  - pytest
  - python=3.13
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - scikit-image
  - pyinstaller
