name: cadiionogram
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipympl
  - joblib
  - matplotlib
  - nodejs
  - numpy
  - pandas
  - polars
  - pip
  - pyarrow
  - pyside6
  - pytest
  - python=3.13
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - nomkl
  - fortls
  - itables
  - scikit-image
  - pyinstaller
  - sphinx
  - numpydoc
  - sphinx-autodoc-typehints
  - pydata-sphinx-theme
  - cython
  - xarray
