name: cadiionogram-release
channels:
  - conda-forge
  - defaults
dependencies:
  - joblib
  - matplotlib
  - nomkl
  - numpy
  - pandas
  - pip
  - pyarrow
  - pyside6
  - pytest
  - python=3.13
  - scipy
  - scikit-image
  - pyinstaller