name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: cadiionogram
          environment-file: environment-build.yml
          auto-activate-base: false

      - name: Run tests
        shell: bash -e {0}
        run: |
          conda activate cadiionogram
          pytest

      - name: Bump version and push tag (Semantic Versioning)
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch   # fallback if no feat/fix/breaking change
          tag_prefix: "v"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
